---

- name: Update APT package manager repositories cache
  apt: 
    update_cache: yes
  become: true

- name: Install OpenJDK Java
  apt: name=openjdk-8-jdk state=present
  become: true

- name: Install Maven
  apt: name=maven state=present
  become: true

- name: copy jar file
  copy: src=../target/api-gateway.jar dest=/home/ubuntu

- name: 'Copy service'
  template:
    src: api.service.j2
    dest: /etc/systemd/system/api.service
    owner: root
    group: root

- name: start api.service
  systemd: state=started name=api.service daemon_reload=yes

#- name: Install Maven
  #shell: "nohup java -Xmx256m -Xss32m -Djava.security.egd=file:/dev/./urandom -jar /home/ubuntu/api-gateway.jar --user=ubuntu &"
  #become: true*/